### ISSUE TITLE
QC Report fails

### ISSUE THREAD

**Issue by jbeast** [wtsi-clarity/wtsi_clarity#228]
Not sure what error message is being generated, but doesn't produce the report!

**Comment by ke4** [comment]
![screen shot 2015-01-21 at 17 05 24](https://cloud.githubusercontent.com/assets/2183410/5840768/d5736972-a18f-11e4-8313-cb1fd810b3cb.png)

**Comment by ke4** [comment]
I think, this report maker has never been tested, because it contains a serious problem (null value), which prevents it to run. I fixed it, but then I'm facing some other bugs. :((((

**Comment by ke4** [comment]
Reopened by mistake, I believe.
