### ISSUE TITLE
Fluidigm 96.96 IFC barcode fails to print

### ISSUE THREAD

**Issue by jbeast** [wtsi-clarity/wtsi_clarity#229]

**Comment by ke4** [comment]
I think this step is badly configured.
At least 2 things are missing from the screen:

Select Barcode printer (a selection list of the available printers)
Barcode Copies (numeric field with a default value)

**Comment by mgcam** [comment]
On 21/01/2015 10:27, Károly Erdős wrote:
>
> I think this step is badly configured.
> At least 2 things are missing from the screen:
>
> Select Barcode printer (a selection list of the available printers)
> Barcode Copies (numeric field with a default value)
>
I do not think the barcode copies field should be compulsory. If no 
value, the script should default to 1. I think it did when I wrote it 
initially

> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wtsi-clarity/wtsi_clarity/issues/229#issuecomment-70815050>.
>




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by ke4** [comment]
Yes, it is default to 1, but we could add the user the possibility to print more than 1 barcode.

**Comment by ke4** [comment]
It was a configuration issue:
The above mentioned fields were missing and also the the configuration of the action was bad.
