### ISSUE TITLE
Unable to assign cherrypick plate to plate delivery

### ISSUE THREAD

**Issue by jbeast** [wtsi-clarity/wtsi_clarity#241]
Script hangs. Doesn't even appear as started in the EPP logs. Script works fine on other steps.

**Comment by mgcam** [comment]
On 27/01/2015 17:06, Chris Smith wrote:
>
> Script hangs. Doesn't even appear as started in the EPP logs. Script 
> works fine on other steps.
>
This happened before, was fixed, as far as I remember, by redefining the 
step in Clarity from scratch. There might be something in old Genologics 
tickets about this - they probably figured out at the end what was wrong 
with that step.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/wtsi-clarity/wtsi_clarity/issues/241>.
>




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jbeast** [comment]
Ahhhh thank you!!! You were right, it was something we had before. Found the original support ticket and it turns out the issue was the same.

In channel it was configured as "ainode01 " instead of "ainode01".

Genologics need to trim their strings!
