### ISSUE TITLE
Barcodes missing signature

### ISSUE THREAD

**Issue by jbeast** [wtsi-clarity/wtsi_clarity#248]
Barcodes usually have a 'signature' in their bottom left corner, generated using the inputs of the process. This seems to have gone missing.

**Comment by jbeast** [comment]
Code seems correct from Clarity side.

@ke4 to check printing service templates

**Comment by ke4** [comment]
Created a new plate template for Clarity in S2 app and updated the label printers in S2 with it.
Still needs to do some code change in Clarity to print with the new templates.

**Comment by ke4** [comment]
Fixed in this pull request: #278.
