### ISSUE TITLE
Post capture pcr setup bed validation need to check workstations assigned

### ISSUE THREAD

**Issue by ke4** [wtsi-clarity/wtsi_clarity#252]
The page URL:  http://web-claritytest-01.internal.sanger.ac.uk:8080/clarity/work-details/26246

Error message:
2 - Bed Verification failed! January 30, 2015 - 11:40 am[Error ID: 30012015114027] Bed verification has failed: Bed 9 barcode (580000009659) differs from config bed barcode (580000006856) 
at .../wtsi_clarity/epp/generic/bed_verifier.pm line 41. 
at .../wtsi_clarity/epp/generic/bed_verifier.pm line 46. 
at .../bin/epp line 58.
 
Input plate  = 1 or 2
Output plate  = 9 or 10

**Comment by jbeast** [comment]
Config was updated this morning.
