### ISSUE TITLE
Post Capture LIB Pooling - bed verification fails

### ISSUE THREAD

**Issue by ke4** [wtsi-clarity/wtsi_clarity#253]
Page URL: http://web-claritytest-01.internal.sanger.ac.uk:8080/clarity/work-details/26301
 
2 - Bed Verification failed! January 30, 2015 - 11:56 am[Error ID: 30012015115604] Bed verification has failed: Bed 1 can not be found in config for specified robot 
at .../wtsi_clarity/epp/generic/bed_verifier.pm line 41. 
at .../wtsi_clarity/epp/generic/bed_verifier.pm line 46. at .../bin/epp line 58.
 
We only need to verify the Input plate 1 and not the 5.

**Comment by jbeast** [comment]
Config added in this morning
