### ISSUE TITLE
Pre Capture Lib Pooling - Bed verification errors

### ISSUE THREAD

**Issue by ke4** [wtsi-clarity/wtsi_clarity#259]
Page URL: .../clarity/work-details/26353
 
Error message:
2 - Bed Verification failed! February 3, 2015 - 11:12 am[Error ID: 03022015111208] 
No callback for action bed_verification 
at .../clarity/bin/epp line 34. 
at .../clarity/bin/epp line 58.

**Comment by ke4** [comment]
It is probably a configuration issue.

**Comment by DaWookie1979** [comment]
nice photo!

**Comment by ke4** [comment]
Reconfigured

**Comment by DaWookie1979** [comment]
2 - Bed Verification failed! February 4, 2015 - 8:00 am
[Error ID: 04022015080014] Bed verification has failed: Can't call method "findvalue" on an undefined value at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/util/roles/clarity_process_io.pm line 94. at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 46. at /local/scratch01/clarity/bin/epp line 58.
