### ISSUE TITLE
Post Capture PCR set up bed validation

### ISSUE THREAD

**Issue by DaWookie1979** [wtsi-clarity/wtsi_clarity#262]
2 - Bed Verification failed! February 4, 2015 - 8:06 am
[Error ID: 04022015080634] Bed verification has failed: Bed 6 can not be found in config for specified robot at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 41. at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 46. at /local/scratch01/clarity/bin/epp line 58.

http://web-claritytest-01.internal.sanger.ac.uk:8080/clarity/work-details/26362

**Comment by DaWookie1979** [comment]
cant attached labels?

**Comment by ke4** [comment]
Fixed the corrupted config file and also changed the field's config in the app.
