### ISSUE TITLE
Post Capture PCR Purification

### ISSUE THREAD

**Issue by DaWookie1979** [wtsi-clarity/wtsi_clarity#263]
2 - Bed Verification failed! February 4, 2015 - 1:10 pm
[Error ID: 04022015130958] Bed verification has failed: Bed 9 barcode (580000009659) differs from config bed barcode (580000006856) at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 41. at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 46. at /local/scratch01/clarity/bin/epp line 58.

http://web-claritytest-01.internal.sanger.ac.uk:8080/clarity/work-details/26364

**Comment by ke4** [comment]
Can somebody tell me the correct name of this step?
Is it 'Post Capture PCR Purification' or 'Post Capture PCR clean up' or 'library pcr purification'?
Because these are not matched in the different configurations...

**Comment by DaWookie1979** [comment]
Correct step in is the title

------------------------------------------------------------------------------------------------------------------------------
Daniel Andrews
Advanced Research Assistant T223
H106 (7761)
The Sanger Institute
Hinxton
Cambs
CB10 1SA


Clarity is like Duct Tape - it has a dark side, it has a light side, and it binds the universe together!

**Comment by DaWookie1979** [comment]
i have renamed the epp to Post Capture PCR Purification.

**Comment by DaWookie1979** [comment]
2 - Bed Verification failed! February 5, 2015 - 3:07 pm
[Error ID: 05022015150704] Bed verification has failed: Bed verification config can not be found for process post_capture_pcr_purification at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 41. at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 46. at /local/scratch01/clarity/bin/epp line 58.

**Comment by ke4** [comment]
reconfigured

**Comment by DaWookie1979** [comment]
Script: 2 - Bed Verification

Run method is called for class wtsi_clarity::epp::generic::bed_verifier, process http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/processes/24-26960

Bed verification has failed: Bed verification config can not be found for process post_capture_pcr_purification at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 41.

at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 46.

[Error ID: 12022015145349] Bed verification has failed: Bed verification config can not be found for process post_capture_pcr_purification at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 41. at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 46. at /local/scratch01/clarity/bin/epp line 58.

**Comment by ke4** [comment]
mistyped has been corrected in the config file
