### ISSUE TITLE
Post Capture Library Pooling - Print Tube Labels failed

### ISSUE THREAD

**Issue by DaWookie1979** [wtsi-clarity/wtsi_clarity#264]
16- Print Tube Labels failed! February 4, 2015 - 1:45 pm
Run method is called for class wtsi_clarity::epp::generic::label_creator, process http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/processes/122-26368

http://web-claritytest-01.internal.sanger.ac.uk:8080/clarity/work-details/26368

**Comment by DaWookie1979** [comment]
prints to plate labels not tube

**Comment by DaWookie1979** [comment]
2 - Bed Verification failed! February 4, 2015 - 1:58 pm
[Error ID: 04022015135840] Bed verification has failed: Bed 1 can not be found in config for specified robot at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 41. at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 46. at /local/scratch01/clarity/bin/epp line 58.

http://web-claritytest-01.internal.sanger.ac.uk:8080/clarity/work-details/26368

**Comment by ke4** [comment]
The 2nd issue in this ticket was a configuration issue, which has been fixed, but the bed verification is still not working. I will raise it as a different ticket.

**Comment by DaWookie1979** [comment]
16- Print Tube Labels failed! February 13, 2015 - 11:37 am
Run method is called for class wtsi_clarity::epp::generic::label_creator, process http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/processes/122-26964

http://web-claritytest-01.internal.sanger.ac.uk:8080/clarity/work-details/26964

**Comment by jbeast** [comment]
There was a line break in the configuration. Took it out and it seemed to sort the problem.
