### ISSUE TITLE
Post Capture Library Pooling - Bed verification is not working

### ISSUE THREAD

**Issue by ke4** [wtsi-clarity/wtsi_clarity#265]
In this step there is no output plate, just tubes. So, we might add a new option to the script which allows to verify only the input bed, like '--only_input 1'.

**Comment by jbeast** [comment]
The fix for this broken bed verification at Pico Assay Plate (many to one) so have had to revert the merge. Reopening this issue.

**Comment by ke4** [comment]
This fix is unfortunately still not working:

There was a configuration issue. I fixed it in the JSON config file, but has other issues:

2 - Bed Verification failed! June 5, 2015 - 3:21 pm
[Error ID: 05062015142100] Bed verification has failed: Expected source plate 2460277824712 to be paired with destination plate 27-8359 
at .../wtsi_clarity/epp/generic/bed_verifier.pm line 48.
at .../wtsi_clarity/epp/generic/bed_verifier.pm line 53.
at .../bin/epp line 58.
