### ISSUE TITLE
Pre Capture Lib Pooling

### ISSUE THREAD

**Issue by DaWookie1979** [wtsi-clarity/wtsi_clarity#268]
2 - Bed Verification failed! February 5, 2015 - 2:35 pm
[Error ID: 05022015143530] Bed verification has failed: Can't call method "findvalue" on an undefined value at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/util/roles/clarity_process_io.pm line 94. at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 46. at /local/scratch01/clarity/bin/epp line 58.

http://web-claritytest-01.internal.sanger.ac.uk:8080/clarity/work-details/26353

**Comment by ke4** [comment]
I think, this pR fixed it: #266
