### ISSUE TITLE
"Real" tag plate fails

### ISSUE THREAD

**Issue by DaWookie1979** [wtsi-clarity/wtsi_clarity#306]
4 - Validate Tag Plate failed! March 2, 2015 - 3:00 pm
Run method is called for class wtsi_clarity::epp::isc::plate_tagger, process http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/processes/24-28704

http://web-claritytest-01.internal.sanger.ac.uk:8080/clarity/work-details/28704

**Comment by ke4** [comment]
Is it a plate which is in production, but not in our test system?
If yes, then that's why it is failing

**Comment by DaWookie1979** [comment]
This is here just as a reminder to fix this when going live

**Comment by DaWookie1979** [comment]
works in production
