### ISSUE TITLE
GetData capture caliper file

### ISSUE THREAD

**Issue by DaWookie1979** [wtsi-clarity/wtsi_clarity#321]
9 - Capture Caliper File failed! March 11, 2015 - 2:25 pm
[Error ID: 11032015142539] XPath error : Undefined namespace prefix error : xmlXPathCompiledEval: evaluation failed at /local/scratch01/clarity/bin/epp line 58.

was working before?

**Comment by DaWookie1979** [comment]
9 - Capture Caliper File failed! September 17, 2015 - 11:52 am
[Error ID: 17092015105229] POST request to http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/samples/batch/update failed: 400 Bad Request Failed to validate the value for 'WTSI Bait Library Name': The value '14M_0671799' is not one of the predefined values 'MG 0454571, Human all exon 50MB, CGP_0588891, DDD_V5_plus, Human all exon V5' at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/util/batch.pm line 69. at /local/scratch01/clarity/bin/epp line 58.

**Comment by jbeast** [comment]
All baits updated to a new valid one.
