### ISSUE TITLE
g311bc1 and g311bc2 printers are not working with Clarity

### ISSUE THREAD

**Issue by ke4** [wtsi-clarity/wtsi_clarity#365]

**Comment by ke4** [comment]
I tried to use these printers with another apps and they are not working with them, too.
The problem is, that their UUIDs are constantly changes with every request.
I also checked it with production and they are fine.
It could be related to a known DB issue in our DEV and UAT environment in S2.
I will try to fix it.

**Comment by ke4** [comment]
Removed unneeded triggers from S2 DEV DB and reinstalled the printers and their templates solved the problem.

**Comment by DaWookie1979** [comment]
ok will try it, thanks
