### ISSUE TITLE
Pre Capture Pooling - Placement is not working

### ISSUE THREAD

**Issue by DaWookie1979** [wtsi-clarity/wtsi_clarity#366]
Script: 13 - Pool Placer

Run method is called for class wtsi_clarity::epp::isc::pooling::pool_placer, process http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/processes/122-37579

POST request to http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/steps/122-37579/placements failed: 400 Bad Request The request contains duplicate placements: [27-6509-H:1, 27-6509-B:1, 27-6509-F:1, 27-6509-D:1, 27-6509-E:1, 27-6509-A:1, 27-6509-B:2, 27-6509-C:1, 27-6509-C:2, 27-6509-G:1, 27-6509-A:2, 27-6509-D:2] at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/isc/pooling/pool_placer.pm line 100.

[Error ID: 22042015103507] POST request to http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/steps/122-37579/placements failed: 400 Bad Request The request contains duplicate placements: [27-6509-H:1, 27-6509-B:1, 27-6509-F:1, 27-6509-D:1, 27-6509-E:1, 27-6509-A:1, 27-6509-B:2, 27-6509-C:1, 27-6509-C:2, 27-6509-G:1, 27-6509-A:2, 27-6509-D:2] at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/isc/pooling/pool_placer.pm line 100. at /local/scratch01/clarity/bin/epp line 58.

when trying to pool 2 or more plates

**Comment by DaWookie1979** [comment]
Script: 13 - Pool Placer


Run method is called for class wtsi_clarity::epp::isc::pooling::pool_placer, process http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/processes/122-38013

POST request to http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/steps/122-38013/placements failed: 400 Bad Request The request contains duplicate placements: [27-6550-E:1, 27-6550-E:1, 27-6550-A:1, 27-6550-G:1, 27-6550-H:1, 27-6550-C:2, 27-6550-F:1, 27-6550-D:1, 27-6550-H:1, 27-6550-D:1, 27-6550-B:1, 27-6550-B:2, 27-6550-E:1, 27-6550-C:2, 27-6550-G:1, 27-6550-F:1, 27-6550-D:2, 27-6550-B:1, 27-6550-D:2, 27-6550-A:2, 27-6550-C:1, 27-6550-A:2, 27-6550-G:1, 27-6550-A:1, 27-6550-A:1, 27-6550-H:1, 27-6550-C:2, 27-6550-C:1, 27-6550-B:2, 27-6550-B:1, 27-6550-D:2, 27-6550-D:1, 27-6550-B:2, 27-6550-A:2, 27-6550-F:1, 27-6550-C:1] at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/isc/pooling/pool_placer.pm line 100.

[Error ID: 23042015104456] POST request to http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/steps/122-38013/placements failed: 400 Bad Request The request contains duplicate placements: [27-6550-E:1, 27-6550-E:1, 27-6550-A:1, 27-6550-G:1, 27-6550-H:1, 27-6550-C:2, 27-6550-F:1, 27-6550-D:1, 27-6550-H:1, 27-6550-D:1, 27-6550-B:1, 27-6550-B:2, 27-6550-E:1, 27-6550-C:2, 27-6550-G:1, 27-6550-F:1, 27-6550-D:2, 27-6550-B:1, 27-6550-D:2, 27-6550-A:2, 27-6550-C:1, 27-6550-A:2, 27-6550-G:1, 27-6550-A:1, 27-6550-A:1, 27-6550-H:1, 27-6550-C:2, 27-6550-C:1, 27-6550-B:2, 27-6550-B:1, 27-6550-D:2, 27-6550-D:1, 27-6550-B:2, 27-6550-A:2, 27-6550-F:1, 27-6550-C:1] at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp at /local/scratch01/clarity/bin/epp line 58.

When pooling 4 plates?

------------------------------------------------------------------------------------------------------------------------------
Daniel Andrews
Advanced Research Assistant T223
H106 (7761)
The Sanger Institute
Hinxton
Cambs
CB10 1SA


Clarity is like Duct Tape - it has a dark side, it has a light side, and it binds the universe together!

**Comment by DaWookie1979** [comment]
Script: 13 - Pool Placer


Run method is called for class wtsi_clarity::epp::isc::pooling::pool_placer, process http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/processes/122-38015

POST request to http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/steps/122-38015/placements failed: 400 Bad Request The request contains duplicate placements: [27-6552-B:1, 27-6552-C:1, 27-6552-E:1, 27-6552-A:1, 27-6552-F:1, 27-6552-D:1] at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/isc/pooling/pool_placer.pm line 100.

[Error ID: 23042015105016] POST request to http://web-claritytest-01.internal.sanger.ac.uk:8080/api/v2/steps/122-38015/placements failed: 400 Bad Request The request contains duplicate placements: [27-6552-B:1, 27-6552-C:1, 27-6552-E:1, 27-6552-A:1, 27-6552-F:1, 27-6552-D:1] at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/isc/pooling/pool_placer.pm line 100. at /local/scratch01/clarity/bin/epp line 58.


Just 2 plates!

Dan

------------------------------------------------------------------------------------------------------------------------------
Daniel Andrews
Advanced Research Assistant T223
H106 (7761)
The Sanger Institute
Hinxton
Cambs
CB10 1SA


Clarity is like Duct Tape - it has a dark side, it has a light side, and it binds the universe together!

**Comment by ke4** [comment]
Not yet deployed. I'm in the process to do it. I'll let you know, when I finished.
The Issue has been closed automatically by Github, because I used Fixes #336, but it does not mean it has been deployed, yet. Please, be patient ;)

**Comment by ke4** [comment]
Deployed.
Please, try it now.
