### ISSUE TITLE
Changing the layout of the tube label and adding signature to it (REOPENED)

### ISSUE THREAD

**Issue by DaWookie1979** [wtsi-clarity/wtsi_clarity#384]
I do not get the top 2 lines of label? 

1) uniq ID of the original parent plate (signature - new element)
2) pooling range
3) could we squeeze in wtsi container signature on (this would fix the bug we found yesterday) It could go on the same line as the pooling range? ie GW8FC A1:H2

**Comment by ke4** [comment]
Fixed with installing the new template to the printers in the laboratories
