### ISSUE TITLE
Production: Validate Tag plate failed

### ISSUE THREAD

**Issue by ke4** [wtsi-clarity/wtsi_clarity#413]
4 - Validate Tag Plate failed! June 2, 2015 - 2:34 pm[Error ID: 02062015133344] POST request to ... failed: 500 Can't connect to ... (Bad hostname) 
Can't connect to ... (Bad hostname) LWP::Protocol::http::Socket: Bad hostname

**Comment by DaWookie1979** [comment]
fixed now
