### ISSUE TITLE
FluidX Container Name doesn't match what Tecan robot needs

### ISSUE THREAD

**Issue by jbeast** [wtsi-clarity/wtsi_clarity#466]
Name of container in Clarity does not EXACTLY match the naming of the container in Evoware Tecan software therefore needs file amendments.

- Manifest change from FluidX0.76ml to FluidX075
- Container name change in Clarity, from FluidX 0.75ml to FluidX075

**Comment by ke4** [comment]
Fixed on July on the server, but not in git. That could be the reason we reverted back with some of our deployment later.
Fixed again today (27/12/2015) in everywhere hopefully (git/test/prod).
